import random
import subprocess

# Generate random arithmetic problems
def generate_arithmetic_problems(num_problems=10):
    problems = []
    answers = []
    for _ in range(num_problems):
        a = random.randint(1, 20)
        b = random.randint(1, 20)
        operator = random.choice(["+", "-", "*", "/"])
        if operator == "/":  # Ensure clean division
            a = a * b
        problem = f"{a} {operator} {b}"
        answer = eval(problem)
        problems.append(problem)
        answers.append(answer)
    return problems, answers

# Generate random linear equations
def generate_linear_equations(num_equations=5):
    problems = []
    answers = []
    for _ in range(num_equations):
        a = random.randint(1, 10)
        b = random.randint(1, 10)
        x = random.randint(1, 10)
        c = a * x + b
        problem = f"{a}x + {b} = {c}"
        answer = x
        problems.append(problem)
        answers.append(answer)
    return problems, answers

# Write problems and answers to a LaTeX file
def write_to_latex(problems, answers, filename="math_test.tex"):
    with open(filename, "w") as f:
        f.write(r"\documentclass[12pt]{article}" + "\n")
        f.write(r"\usepackage[utf8]{inputenc}" + "\n")
        f.write(r"\usepackage{amsmath}" + "\n")
        f.write(r"\title{Math Practice Test}" + "\n")
        f.write(r"\author{Generated by Python}" + "\n")
        f.write(r"\date{\today}" + "\n")
        f.write(r"\begin{document}" + "\n")
        f.write(r"\maketitle" + "\n")
        
        # Problems Section
        f.write(r"\section*{Problems}" + "\n")
        f.write(r"\begin{enumerate}" + "\n")
        for problem in problems:
            f.write(rf"  \item {problem}" + "\n")
        f.write(r"\end{enumerate}" + "\n")
        
        # Answer Key
        f.write(r"\newpage" + "\n")
        f.write(r"\section*{Answer Key}" + "\n")
        f.write(r"\begin{enumerate}" + "\n")
        for answer in answers:
            f.write(rf"  \item {answer}" + "\n")
        f.write(r"\end{enumerate}" + "\n")
        
        f.write(r"\end{document}" + "\n")

# Main script
if __name__ == "__main__":
    # Generate problems
    arithmetic_problems, arithmetic_answers = generate_arithmetic_problems(10)
    linear_problems, linear_answers = generate_linear_equations(5)
    
    # Combine all problems and answers
    all_problems = arithmetic_problems + linear_problems
    all_answers = arithmetic_answers + linear_answers
    
    # Write to LaTeX file
    write_to_latex(all_problems, all_answers, filename="math_test.tex")
    
    # Compile LaTeX to PDF (requires pdflatex installed locally)
    try:
        subprocess.run(["pdflatex", "math_test.tex"], check=True)
        print("PDF successfully generated as math_test.pdf!")
    except FileNotFoundError:
        print("pdflatex not found. Please compile math_test.tex manually.")
